--DATOS TERRENO
insert into terreno values ('T','TIERRA');
insert into terreno values ('A','AGUA');
insert into terreno values ('.','Aire');
insert into terreno values ('P','Piedra');
insert into terreno values ('B','Caja Bomba');

SELECT * FROM TERRENO;

--DATOS TABLERO 15X150
INSERT  INTO TABLERO  values (1,1,1);
INSERT  INTO TABLERO  values (1,1,2);
INSERT  INTO TABLERO  values (1,1,3);
INSERT  INTO TABLERO  values (1,1,4);
INSERT  INTO TABLERO  values (1,2,1);
INSERT  INTO TABLERO  values (1,2,2);
INSERT  INTO TABLERO  values (1,2,3);
INSERT  INTO TABLERO  values (1,2,4);
INSERT  INTO TABLERO  values (1,3,1);
INSERT  INTO TABLERO  values (1,3,2);
INSERT  INTO TABLERO  values (1,3,3);
INSERT  INTO TABLERO  values (1,3,4);

SELECT * FROM TABLERO;


--------------insert partida
insert into partida  values (1,30,'MEDIA','0','0');

SELECT * FROM partida;

-------EQUIPO
INSERT INTO EQUIPO VALUES (1,'EQUIPO A',1,'H','W',0,0);
INSERT INTO EQUIPO VALUES (2,'EQUIPO B',1,'H','R',0,0);
INSERT INTO EQUIPO VALUES (3,'EQUIPO C',1,'M','L',0,0);
INSERT INTO EQUIPO VALUES (4,'EQUIPO D',1,'H','H',0,0);

SELECT * FROM equipo;


----------POS PARTIDA
INSERT INTO  POSICION_PARTIDA VALUES (1,1,1,1,1,2,NULL,'.');
INSERT INTO  POSICION_PARTIDA VALUES (1,1,2,1,1,2,NULL,'.');
INSERT INTO  POSICION_PARTIDA VALUES (1,1,3,1,1,4,NULL,'.');
INSERT INTO  POSICION_PARTIDA VALUES (1,1,4,1,1,2,NULL,'.');
INSERT INTO  POSICION_PARTIDA VALUES (1,2,1,1,1,2,NULL,'T');
INSERT INTO  POSICION_PARTIDA VALUES (1,2,2,1,1,4,NULL,'T');
INSERT INTO  POSICION_PARTIDA VALUES (1,2,3,1,1,2,NULL,'T');
INSERT INTO  POSICION_PARTIDA VALUES (1,2,4,1,1,2,NULL,'T');
INSERT INTO  POSICION_PARTIDA VALUES (1,3,1,1,1,4,NULL,'A');
INSERT INTO  POSICION_PARTIDA VALUES (1,3,2,1,1,2,NULL,'A');
INSERT INTO  POSICION_PARTIDA VALUES (1,3,3,1,1,2,NULL,'A');
INSERT INTO  POSICION_PARTIDA VALUES (1,3,4,1,1,4,NULL,'A');

truncate table POSICION_PARTIDA;

select * from posicion_partida;










 SELECT COORDENADA_X  FROM posicion_partida WHERE ID=1;


