drop table PARTIDA;
CREATE TABLE PARTIDA { /* una partida tiene un tablero */
    ID NUMBER (5) NOT NULL,
    DURACION NUMBER (2) NOT NULL,
    TABLEROID NUMBER (5) REFERENCES TABLERO (ID),--NO ESTOY SEGURO DE ESTO.
    FINALIZADA BOOLEAN NOT NULL

     CONSTRAINT PK_PARTIDA PRIMARY KEY (ID)
}

drop table TABLERO;
CREATE TABLE TABLERO { 
    ID NUMBER (5) NOT NULL,
    MAX_Y NUMBER (3) NOT NULL,
    MAX_X NUMBER (3) NOT NULL

     CONSTRAINT PK_TABLERO PRIMARY KEY (ID)
}

CREATE TABLE TERRENO {
    ID NUMBER (5) NOT NULL,
    TIPO  VARCHAR (15) NOT NULL /* aire, tierra, etc */
     CONSTRAINT PK_TERRENO PRIMARY KEY (ID)
}

CREATE TABLE CELDA { /* puede tener un terreno y existe la posibilidad de que exista un gusano en el */
--CREO Q NO LA VAMOS A USAR ESTA TABLA
}

CREATE TABLE CELDA_PARTIDA { /* representa una de las celdas en el tablero */
    COORDENADA_X NUMBER (3) NOT NULL,
    COORDENADA_Y NUMBER (3) NOT NULL
    PARTIDAID NUMBER (5) NOT NULL, --AGREGAR FK
    GUSANOID NUMBER (5)  NULL,
    TERRENOID NUMBER (5) NOT NULL

     CONSTRAINT PK_CELDA_PARTIDA PRIMARY KEY (COORDENADA_X,COORDENADA_Y,PARTIDAID)
     CONSTRAINT FK_PARTIDA FOREIGN KEY (PARTIDAID) REFERENCES PARTIDA(ID)
     CONSTRAINT FK_TERRENO FOREIGN KEY (TERRENOID) REFERENCES TERRENO(ID)
     CONSTRAINT FK_GUSANO FOREIGN KEY (GUSANOID) REFERENCES GUSANO(ID)--PREGUNTAR EN CLASE CAMPO NULLABLE PUEDE TENER FK?
}

CREATE TABLE TURNO {    /* hay que definir */
}

CREATE TABLE JUGADOR { --revisar si lo precisamos o no solo con equipo manejamos todo con un atributo extra
    ID NUMBER (5) PRIMARY KEY,
    NOMBRE VARCHAR (10) NOT NULL
}

CREATE TABLE EQUIPO { /* Un equipo representa a un jugador */
    ID NUMBER (5) PRIMARY KEY,
    NOMBRE VARCHAR (10) NOT NULL,
    JUGADORID NUMBER (5) REFERENCES JUGADOR (ID),
    ASESINATOS NUMBER (2),
    MUERTES NUMBER (2)
}

CREATE TABLE PARTICIPA { /* un equipo participa en una partida */
    PARTIDAID NUMBER (5) REFERENCES PARTIDA (ID),
    EQUIPOID NUMBER (5) REFERENCES EQUIPO (ID),
    CONSTRAINT PK_Participan PRIMARY KEY (PARTIDAID, EQUIPOID)
}

CREATE TABLE GUSANO {
    ID NUMBER (5) NOT NULL,
    PARTIDAID NUMBER (5) NOT NULL,
    EQUIPOID NUMBER (5) NOT NULL, 
    VIDA NUMBER (3),
    CONSTRAINT PK_Gusano PRIMARY KEY (ID,PARTIDAID, EQUIPOID)
    CONSTRAINT FK_PARTICIPAN FOREIGN KEY (PARTIDAID, EQUIPOID) REFERENCES PARTICIPA(PARTIDAID, EQUIPOID)
}

CREATE TABLE ARMA {
    ID NUMBER (5) NOT NULL,
    PARTIDAID NUMBER (5) NOT NULL,
    EQUIPOID NUMBER (5) NOT NULL, 
    NOMBRE VARCHAR (25) NOT NULL
 
    CONSTRAINT PK_ARMA PRIMARY KEY (ID,PARTIDAID, EQUIPOID)
    CONSTRAINT FK_PARTICIPAN FOREIGN KEY (PARTIDAID, EQUIPOID) REFERENCES PARTICIPA(PARTIDAID, EQUIPOID)
}


CREATE TABLE ESTADISTICA { /* hay que definir */ -- LAS MANEJAMOS EN EL EQUPO Y NOS OLVIDAMOS DE ESTA TABLA ?
}