drop table PARTIDA;
CREATE TABLE PARTIDA { /* una partida tiene un tablero */
    ID NUMBER (5) NOT NULL,
    DURACION NUMBER (2) NOT NULL,
    DIFICULLTAD VARCHAR (20) NOT NULL,
    TABLEROID NUMBER (5) REFERENCES TABLERO (ID),--NO ESTOY SEGURO DE ESTO.
    FINALIZADA BOOLEAN NOT NULL,
    TURNO NUMBER (18) NOT NULL,

     CONSTRAINT PK_PARTIDA PRIMARY KEY (ID)
}

drop table TABLERO;
CREATE TABLE TABLERO { 
    ID NUMBER (5) NOT NULL,
    MAX_Y NUMBER (3) NOT NULL,
    MAX_X NUMBER (3) NOT NULL,
    COORDENADA_X NUMBER (3) NOT NULL,
    COORDENADA_Y NUMBER (3) NOT NULL

     CONSTRAINT PK_TABLERO PRIMARY KEY (ID,COORDENADA_X,COORDENADA_Y)
}

CREATE TABLE TERRENO {
    ID NUMBER (5) NOT NULL,
    TIPO  VARCHAR (15) NOT NULL
     CONSTRAINT PK_TERRENO PRIMARY KEY (ID)
}

CREATE TABLE CELDA { /* puede tener un terreno y existe la posibilidad de que exista un gusano en el */
--CREO Q NO LA VAMOS A USAR ESTA TABLA
}

CREATE TABLE POSICION_PARTIDA { /* representa una de las celdas en el tablero */
    ID  NUMBER (3) NOT NULL,
    COORDENADA_X NUMBER (3) NOT NULL,
    COORDENADA_Y NUMBER (3) NOT NULL
    PARTIDAID NUMBER (5) NOT NULL, 
    GUSANOID NUMBER (5)  NULL,
    TERRENOID NUMBER (5) NOT NULL

     CONSTRAINT PK_CELDA_PARTIDA PRIMARY KEY (ID,COORDENADA_X,COORDENADA_Y,PARTIDAID)
     CONSTRAINT FK_PARTIDA FOREIGN KEY (PARTIDAID) REFERENCES PARTIDA(ID)
     CONSTRAINT FK_TERRENO FOREIGN KEY (TERRENOID) REFERENCES TERRENO(ID)
     CONSTRAINT FK_GUSANO FOREIGN KEY (GUSANOID) REFERENCES GUSANO(ID)--PREGUNTAR EN CLASE CAMPO NULLABLE PUEDE TENER FK?
}

CREATE TABLE TURNO {    /* hay que definir */
}

CREATE TABLE JUGADOR { --revisar si lo precisamos o no solo con equipo manejamos todo con un atributo extra
    ID NUMBER (5) PRIMARY KEY,
    NOMBRE VARCHAR (10) NOT NULL
}

CREATE TABLE EQUIPO { /* Un equipo representa a un jugador */
    ID NUMBER (5) PRIMARY KEY,
    NOMBRE VARCHAR (10) NOT NULL,
    PARTIDAID NUMBER (5) REFERENCES PARTIDA (ID),
    JUGADORID NUMBER (5) REFERENCES JUGADOR (ID),
    ASESINATOS NUMBER (2),
    MUERTES NUMBER (2)
}

CREATE TABLE GUSANO {
    ID NUMBER (5) NOT NULL,
    EQUIPOID NUMBER (5) NOT NULL, 
    VIDA NUMBER (3),
    CONSTRAINT PK_Gusano PRIMARY KEY (ID,PARTIDAID, EQUIPOID)
    CONSTRAINT FK_EQUIPOID FOREIGN KEY (EQUIPOID) REFERENCES EQUIPO(ID)
}

CREATE TABLE ARMA {
    ID NUMBER (5) NOT NULL,
    DMG NUMBER (5) NOT NULL,
    NOMBRE VARCHAR (25) NOT NULL
 
    CONSTRAINT PK_ARMA PRIMARY KEY (ID,NOMBRE)
}

CREATE TABLE ARMA_EQUIPO {
    ID NUMBER (5) NOT NULL,
    ARMAID NUMBER (5) REFERENCES ARMA (ID),
    EQUIPOID NUMBER (5) REFERENCES EQUIPO (ID),
 
    CONSTRAINT ARMA_EQUIPO PRIMARY KEY (ID,ARMAID,EQUIPOID)
}
